language: python

dist: bionic

matrix:
  include:
  - python: '2.7'
  - python: '3.4'
  - python: '3.5'
  - python: '3.6'
  - python: '3.7'
  - python: '3.8-dev'
  allow_failures:
  - python: '3.8-dev'

before_install:
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends python-apsw 
  - mkdir /opt/acestream
  - cd /opt/acestream
  - curl -s http://acestream.org/downloads/linux/acestream_3.1.49_debian_9.9_x86_64.tar.gz | tar xzf - 
  - ./acestreamengine --client-console --log-file acestream.log 2>&1 & cd -
  - pip install --disable-pip-version-check --upgrade pip setuptools
  - pip install pytest-cov pytest-flake8 codecov

install:
  - pip install .

script:
  - python -m pytest --cov=. --flake8

after_success:
  - codecov
